version: "3.8"

services:
  backend:
    build: /home/sportnews-user/SportNewsAI/sportnews/backend
    container_name: sportnews-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - /home/sportnews-user/SportNewsAI/.env
    networks:
      - sportnews-net

  frontend:
    build: /home/sportnews-user/SportNewsAI/sportnews/frontend
    container_name: sportnews-frontend
    restart: always
    volumes:
      - /etc/letsencrypt/live/sport.event-fit.it:/etc/letsencrypt/live/sport.event-fit.it:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - sportnews-net

networks:
  sportnews-net:
    driver: bridge